# Generated by Django 4.2.7 on 2023-11-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='gender',
        ),
    ]
