# Generated by Django 4.2.7 on 2023-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_review_date_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type_of_classes',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Dance', 'Dance')], default='Yoga', max_length=10),
        ),
    ]
