# Generated by Django 4.2.7 on 2023-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_timetable_monday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='monday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
    ]
