# Generated by Django 4.2.7 on 2023-12-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_timetable_monday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='friday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='saturday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sunday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thursday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tuesday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednesday',
            field=models.CharField(default='-', editable=False, max_length=10),
        ),
    ]
