# Generated by Django 4.2.7 on 2023-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', 'один'), ('2', 'два'), ('3', 'три'), ('4', 'четыре'), ('5', 'пять')]),
        ),
    ]
