# Generated by Django 4.2.7 on 2023-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('&#9733', '1'), ('**', '2'), ('***', '3'), ('****', '4'), ('&#9733;&#9733;&#9733;&#9733;&#9733;', '5')], max_length=100),
        ),
    ]
